export const EMPLEADO_FIND_ALL = 'EMPLEADO_FIND_ALL';

export const EMPLEADO_FIND_BY_ID = 'EMPLEADO_FIND_BY_ID';
export const EMPLEADO_DELETE_BY_ID = 'EMPLEADO_DELETE_BY_ID';
export const EMPLEADO_PAGINATED_SEARCH = 'EMPLEADO_PAGINATED_SEARCH';
